Integrate with Hugging Face
facebookresearch/segment-anything-2 pull request #128
Opened 2024-08-03 13:05 UTC by NielsRogge

This PR fixes #1. It aims to make it possible to load any SAM 2 model directly from the hub.

The checkpoints are already part of the facebook org:
* https://huggingface.co/facebook/sam2-hiera-tiny
* https://huggingface.co/facebook/sam2-hiera-small
* https://huggingface.co/facebook/sam2-hiera-base-plus
* https://huggingface.co/facebook/sam2-hiera-large.

This PR allows to do the following:

```python
from sam2.sam2_image_predictor import SAM2ImagePredictor

predictor = SAM2ImagePredictor.from_pretrained("facebook/sam2-hiera-small")
```

This also ensures that download stats work, meaning you'll be able to see how many times people actually load one of these checkpoints from the hub.

To do:

- [ ] update README to link to HF artifacts
- [ ] update notebooks (?)

2024-08-04 10:59 UTC, bhack commented
Is this also in the to-do list at https://github.com/huggingface/transformers/pull/32394

2024-08-05 01:55 UTC, haithamkhedr requested changes
@NielsRogge Thanks for supporting ckpt download from HF. Can we make `huggingface_hub` a soft dependency?

2024-08-05 01:55 UTC, haithamkhedr commented on sam2/sam2_image_predictor.py
> +from sam2.build_sam import build_sam2_hf
Similarly, lets make this optional

2024-08-05 01:55 UTC, haithamkhedr commented on sam2/build_sam.py
> +from huggingface_hub import hf_hub_download
Can we move this inside the function to make this an optional dependency?

2024-08-05 17:09 UTC, haithamkhedr commented on README.md
I think it would be better to have a seperate README section for HF checkpoints paths as well as usage, leaving the original sample usage as is (since `huggingface_hub` is also an optional dependancy)

2024-08-05 23:22 UTC, haithamkhedr commented on sam2/build_sam.py
> +    return build_sam2_video_predictor(config_file=config_name, ckpt_path=ckpt_path, **kwargs)
This should be a call to `build_sam2` ?

2024-08-05 23:22 UTC, haithamkhedr commented on sam2/build_sam.py
> +    config_file = hf_hub_download(repo_id=model_id, filename=f"{model_id}.yaml")
We also need a dictionary mapping `model_id` to config names similar to `model_id_to_filenames`

2024-08-07 15:36 UTC, haithamkhedr commented on README.md
> +    masks, _, _ = predictor.predict(<input_prompts>)
Can we replace this with video predictor usage:

```python
with torch.inference_mode(), torch.autocast("cuda", dtype=torch.bfloat16):
    state = predictor.init_state(<your_video>)

    # add new prompts and instantly get the output on the same frame
    frame_idx, object_ids, masks = predictor.add_new_points(state, <your_prompts>):

    # propagate the prompts to get masklets throughout the video
    for frame_idx, object_ids, masks in predictor.propagate_in_video(state):
```

2024-08-07 15:54 UTC, haithamkhedr approved these changes
Thanks for adding support to load the models through HF hub.

2024-08-07 15:54 UTC, merged

2024-08-07 16:01 UTC, giswqs commented
This is great! Is there a plan to make it compatible with transformers, like SAM 1?

https://huggingface.co/docs/transformers/en/tasks/mask_generation

2024-08-07 16:07 UTC, NielsRogge commented
Yes there is, the authors are adding a PR here: https://github.com/huggingface/transformers/pull/32394

2024-08-07 16:09 UTC, giswqs commented
Fantastic! Can't wait for the PR to be merged!

2024-08-12 23:11 UTC, leonmkim commented
Sorry potentially dumb question, but should this [line](https://github.com/facebookresearch/segment-anything-2/blob/dce7b5446f260cef9fdf3d3f1bc81519302d386f/sam2/sam2_video_predictor.py#L124) in the video predictor be changed from `return cls(sam_model)` to `return sam_model`? It seems like the former would work for the image predictor based on its constructor but not the video predictor. But I could be wrong :p

2024-08-13 00:04 UTC, haithamkhedr commented
> Sorry potentially dumb question, but should this [line](https://github.com/facebookresearch/segment-anything-2/blob/dce7b5446f260cef9fdf3d3f1bc81519302d386f/sam2/sam2_video_predictor.py#L124) in the video predictor be changed from `return cls(sam_model)` to `return sam_model`? It seems like the former would work for the image predictor based on its constructor but not the video predictor. But I could be wrong :p

Good catch. Fixed in #205